@startuml ClassDiagram_Matchmaking
left to right direction

class Usuario {
    +UUID id
    +String email
    +String passwordHash
    +String rol
    +String estadoCuenta
}

class PerfilTransportista {
    +UUID id
    +String dni
    +String nombres
    +String telefono
    +String estadoVerificacion
}

class PerfilEmprendedor {
    +UUID id
    +String razonSocial
    +String ruc
    +String direccionComercial
}

class Vehiculo {
    +UUID id
    +String placa
    +String tipoCarroceria
    +Float capacidadCargaKg
}

class RutaRetorno {
    +UUID id
    +String origen
    +String destino
    +DateTime fechaSalida
    +Float capacidadDisponibleKg
    +String estado
}

class SolicitudEnvio {
    +UUID id
    +String origen
    +String destino
    +Float pesoKg
    +String estado
}

class PropuestaMatch {
    +UUID id
    +Float montoOfrecido
    +Float tarifaAcordada
    +String estado
}

class ViajeLogistico {
    +UUID id
    +DateTime fechaRecojoReal
    +DateTime fechaEntrega
    +String estadoViaje
}

class Incidencia {
    +UUID id
    +String tipoIncidencia
    +String descripcion
    +Boolean atendida
}

class TransaccionPago {
    +UUID id
    +Float montoTotal
    +Float comisionPlataforma
    +String estadoPago
}

class Calificacion {
    +UUID id
    +Int puntuacion
    +String comentario
}

Usuario "1" --> "0..1" PerfilTransportista : tiene
Usuario "1" --> "0..1" PerfilEmprendedor : tiene
PerfilTransportista "1" --> "1..*" Vehiculo : registra
PerfilTransportista "1" --> "0..*" RutaRetorno : publica
Vehiculo "1" --> "0..*" RutaRetorno : asignado a
PerfilEmprendedor "1" --> "0..*" SolicitudEnvio : solicita
SolicitudEnvio "1" --> "0..*" PropuestaMatch : recibe
RutaRetorno "1" --> "0..*" PropuestaMatch : genera
PropuestaMatch "1" --> "1" ViajeLogistico : se convierte en
ViajeLogistico "1" *-- "0..*" Incidencia : registra
ViajeLogistico "1" --> "1" TransaccionPago : genera
ViajeLogistico "1" --> "0..2" Calificacion : recibe
@enduml